# WSR-88D site list from NCEI HOMR nexrad-stations.txt (NEXRAD type only)
SITES = [
    ('KABR', 'Aberdeen', 'SD'),
    ('KABX', 'Albuquerque', 'NM'),
    ('KAKQ', 'Norfolk Rich', 'VA'),
    ('KAMA', 'Amarillo', 'TX'),
    ('KAMX', 'Miami', 'FL'),
    ('KAPX', 'Gaylord', 'MI'),
    ('KARX', 'La Crosse', 'WI'),
    ('KATX', 'Seattle', 'WA'),
    ('KBBX', 'Beale Afb', 'CA'),
    ('KBGM', 'Binghamton', 'NY'),
    ('KBHX', 'Eureka', 'CA'),
    ('KBIS', 'Bismarck', 'ND'),
    ('KBLX', 'Billings', 'MT'),
    ('KBMX', 'Birmingham', 'AL'),
    ('KBOX', 'Boston', 'MA'),
    ('KBRO', 'Brownsville', 'TX'),
    ('KBUF', 'Buffalo', 'NY'),
    ('KBYX', 'Key West', 'FL'),
    ('KCAE', 'Columbia', 'SC'),
    ('KCBW', 'Houlton', 'ME'),
    ('KCBX', 'Boise', 'ID'),
    ('KCCX', 'State College', 'PA'),
    ('KCLE', 'Cleveland', 'OH'),
    ('KCLX', 'Charleston', 'SC'),
    ('KCRI', 'Roc Faa Redundant Rda 1', 'OK'),
    ('KCRP', 'Corpus Christi', 'TX'),
    ('KCXX', 'Burlington', 'VT'),
    ('KCYS', 'Cheyenne', 'WY'),
    ('KDAX', 'Sacramento', 'CA'),
    ('KDDC', 'Dodge City', 'KS'),
    ('KDFX', 'Laughlin Afb', 'TX'),
    ('KDGX', 'Jackson Brandon', 'MS'),
    ('KDIX', 'Philadelphia', 'NJ'),
    ('KDLH', 'Duluth', 'MN'),
    ('KDMX', 'Des Moines', 'IA'),
    ('KDOX', 'Dover Afb', 'DE'),
    ('KDTX', 'Detroit', 'MI'),
    ('KDVN', 'Davenport', 'IA'),
    ('KDYX', 'Dyess Afb', 'TX'),
    ('KEAX', 'Kansas City', 'MO'),
    ('KEMX', 'Tucson', 'AZ'),
    ('KENX', 'Albany', 'NY'),
    ('KEOX', 'Fort Rucker', 'AL'),
    ('KEPZ', 'El Paso', 'NM'),
    ('KESX', 'Las Vegas', 'NV'),
    ('KEVX', 'Eglin Afb', 'FL'),
    ('KEWX', 'Austin San Antonio', 'TX'),
    ('KEYX', 'Edwards', 'CA'),
    ('KFCX', 'Roanoke', 'VA'),
    ('KFDR', 'Altus Afb', 'OK'),
    ('KFDX', 'Cannon Afb', 'NM'),
    ('KFFC', 'Atlanta', 'GA'),
    ('KFSD', 'Sioux Falls', 'SD'),
    ('KFSX', 'Flagstaff', 'AZ'),
    ('KFTG', 'Denver Front Range Ap', 'CO'),
    ('KFWS', 'Dallas', 'TX'),
    ('KGGW', 'Glasgow', 'MT'),
    ('KGJX', 'Grand Junction', 'CO'),
    ('KGLD', 'Goodland', 'KS'),
    ('KGRB', 'Green Bay', 'WI'),
    ('KGRK', 'Fort Hood', 'TX'),
    ('KGRR', 'Grand Rapids', 'MI'),
    ('KGSP', 'Greer', 'SC'),
    ('KGWX', 'Columbus Afb', 'MS'),
    ('KGYX', 'Portland', 'ME'),
    ('KHDC', 'Hammond Municipal Airport', 'LA'),
    ('KHDX', 'Holloman Afb', 'NM'),
    ('KHGX', 'Houston', 'TX'),
    ('KHNX', 'San Joaquin Valley', 'CA'),
    ('KHPX', 'Fort Campbell', 'KY'),
    ('KHTX', 'Huntsville', 'AL'),
    ('KICT', 'Wichita', 'KS'),
    ('KICX', 'Cedar City', 'UT'),
    ('KILN', 'Cincinnati', 'OH'),
    ('KILX', 'Lincoln', 'IL'),
    ('KIND', 'Indianapolis', 'IN'),
    ('KINX', 'Tulsa', 'OK'),
    ('KIWA', 'Phoenix', 'AZ'),
    ('KIWX', 'Fort Wayne', 'IN'),
    ('KJAX', 'Jacksonville', 'FL'),
    ('KJGX', 'Robins Afb', 'GA'),
    ('KJKL', 'Jackson', 'KY'),
    ('KLBB', 'Lubbock', 'TX'),
    ('KLCH', 'Lake Charles', 'LA'),
    ('KLGX', 'Langley Hill Nw Washington', 'WA'),
    ('KLIX', 'New Orleans', 'LA'),
    ('KLNX', 'North Platte', 'NE'),
    ('KLOT', 'Chicago', 'IL'),
    ('KLRX', 'Elko', 'NV'),
    ('KLSX', 'St Louis', 'MO'),
    ('KLTX', 'Wilmington', 'NC'),
    ('KLVX', 'Louisville', 'KY'),
    ('KLWX', 'Sterling', 'VA'),
    ('KLZK', 'Little Rock', 'AR'),
    ('KMAF', 'Midland Odessa', 'TX'),
    ('KMAX', 'Medford', 'OR'),
    ('KMBX', 'Minot Afb', 'ND'),
    ('KMHX', 'Morehead City', 'NC'),
    ('KMKX', 'Milwaukee', 'WI'),
    ('KMLB', 'Melbourne', 'FL'),
    ('KMOB', 'Mobile', 'AL'),
    ('KMPX', 'Minneapolis', 'MN'),
    ('KMQT', 'Marquette', 'MI'),
    ('KMRX', 'Knoxville', 'TN'),
    ('KMSX', 'Missoula', 'MT'),
    ('KMTX', 'Salt Lake City', 'UT'),
    ('KMUX', 'San Francisco', 'CA'),
    ('KMVX', 'Grand Forks', 'ND'),
    ('KMXX', 'Maxwell Afb', 'AL'),
    ('KNKX', 'San Diego', 'CA'),
    ('KNQA', 'Memphis', 'TN'),
    ('KOAX', 'Omaha', 'NE'),
    ('KOHX', 'Nashville', 'TN'),
    ('KOKX', 'New York City', 'NY'),
    ('KOTX', 'Spokane', 'WA'),
    ('KOUN', 'Norman Nssl', 'OK'),
    ('KPAH', 'Paducah', 'KY'),
    ('KPBZ', 'Pittsburgh', 'PA'),
    ('KPDT', 'Pendleton', 'OR'),
    ('KPOE', 'Fort Polk', 'LA'),
    ('KPUX', 'Pueblo', 'CO'),
    ('KRAX', 'Raleigh Durham', 'NC'),
    ('KRGX', 'Reno', 'NV'),
    ('KRIW', 'Riverton', 'WY'),
    ('KRLX', 'Charleston', 'WV'),
    ('KRTX', 'Portland', 'OR'),
    ('KSFX', 'Pocatello', 'ID'),
    ('KSGF', 'Springfield', 'MO'),
    ('KSHV', 'Shreveport', 'LA'),
    ('KSJT', 'San Angelo', 'TX'),
    ('KSOX', 'Santa Ana Mountains', 'CA'),
    ('KSRX', 'Fort Smith', 'AR'),
    ('KTBW', 'Tampa', 'FL'),
    ('KTFX', 'Great Falls', 'MT'),
    ('KTLH', 'Tallahassee', 'FL'),
    ('KTLX', 'Oklahoma City', 'OK'),
    ('KTWX', 'Topeka', 'KS'),
    ('KTYX', 'Fort Drum', 'NY'),
    ('KUDX', 'Rapid City', 'SD'),
    ('KUEX', 'Hastings', 'NE'),
    ('KVAX', 'Moody Afb', 'GA'),
    ('KVBX', 'Vandenberg Afb', 'CA'),
    ('KVNX', 'Vance Afb', 'OK'),
    ('KVTX', 'Los Angeles', 'CA'),
    ('KVWX', 'Evansville', 'IN'),
    ('KYUX', 'Yuma', 'AZ'),
    ('LPLA', 'Lajes Ab', ''),
    ('PABC', 'Bethel Faa', 'AK'),
    ('PACG', 'Sitka', 'AK'),
    ('PAEC', 'Nome', 'AK'),
    ('PAHG', 'Anchorage', 'AK'),
    ('PAIH', 'Middleton Island', 'AK'),
    ('PAKC', 'King Salmon', 'AK'),
    ('PAPD', 'Fairbanks', 'AK'),
    ('PGUA', 'Andersen Afb Agana', 'GU'),
    ('PHKI', 'South Kauai', 'HI'),
    ('PHKM', 'Kamuela', 'HI'),
    ('PHMO', 'Molokai', 'HI'),
    ('PHWA', 'South Shore', 'HI'),
    ('RKJK', 'Kunsan', ''),
    ('RKSG', 'Camp Humphreys', ''),
    ('RODN', 'Kadena', ''),
    ('TJUA', 'San Juan', 'PR'),
]
